# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AurelioAvila.TweakyDriver
PackageVersion: 0.1.14
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
UpgradeBehavior: install
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AurelioAvila/Tweaky-Driver-Releases/releases/download/v0.1.14/Tweaky-Driver-0.1.14-x64-setup.exe
  InstallerSha256: 9B56CED8E6B8A1A1F25329C3EEE03510348AD4E53DCA1948C2B5B2E17B27BD91
ManifestType: installer
ManifestVersion: 1.12.0
