# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AurelioAvila.PCTweakerUninstaller
PackageVersion: 0.12.4
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
UpgradeBehavior: install
ProductCode: PC Tweaker Uninstaller
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- DisplayName: PC Tweaker Uninstaller
  Publisher: Aurelio Avila
  ProductCode: PC Tweaker Uninstaller
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\PC Tweaker Uninstaller'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AurelioAvila/pc-tweaker-uninstaller/releases/download/v0.12.4/PC.Tweaker.Uninstaller_0.12.4_x64-setup.exe
  InstallerSha256: 1BB98EEEC1925A1A3B683BCE24D0AD41BB05B7FA8583E689725E29919AB50923
ManifestType: installer
ManifestVersion: 1.12.0
