# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AurelioAvila.TweakyDriver
PackageVersion: 0.1.15
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
UpgradeBehavior: install
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AurelioAvila/Tweaky-Driver-Releases/releases/download/v0.1.15/Tweaky-Driver-0.1.15-x64-setup.exe
  InstallerSha256: CC5E42C4A9F1DD2AB0AADC59955A107A06EDE688C7EBF7C78E5F8BEC85B8D225
ManifestType: installer
ManifestVersion: 1.12.0
