# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AurelioAvila.TweakyDriver
PackageVersion: 0.1.8
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AurelioAvila/Tweaky-Driver-Releases/releases/download/v0.1.8/Tweaky-Driver-0.1.8-x64-setup.exe
  InstallerSha256: E231FB003698B2114924FE113DD85B3F0940B3DA07BF3A0267D04ECFAABB57EA
ManifestType: installer
ManifestVersion: 1.12.0
