# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AurelioAvila.PCTweakerUninstaller
PackageVersion: 0.12.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AurelioAvila/pc-tweaker-uninstaller/releases/download/v0.12.0/PC.Tweaker.Uninstaller_0.12.0_x64-setup.exe
  InstallerSha256: 0E501272F77D73069A89BF37BBF6ECA68BF968ECCB7AF9329905180B0359641E
ManifestType: installer
ManifestVersion: 1.12.0
